spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: root
    password:
  batch:
    jdbc:
      initialize-schema: always # batch 스키마 자동 생성
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: create
  servlet:
    multipart:
      max-file-size: 5MB # 단일 파일 업로드 용량 제한, default : 1mb
      max-request-size: 5MB  # 모든 파일 업로드 용량 제한, default : 1mb
  mail:
    host: smtp.gmail.com  # SMTP 서버 호스트, 일일 전송 제한 100개
    port: 587 # SMTP 서버 포트
    username: ${MAIL_USERNAME}  # SMTP 서버 로그인 아이디
    password: ${MAIL_PASSWORD}  # SMTP 서버 로그인 패스워드
    properties:
      mail:
        smtp:
          auth: true  # 사용자 인증 시도 여부, default : false
          timeout: 5000 # Socket Read Timeout 시간(ms), default : infinity
          starttls:
            enable: true  # StartTLS 활성화 여부, default : false
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
            scope: email, profile
mail:
  address:
    admin: admin@gmail.com  # 관리자 권한 계정
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${JWT_REFRESH_TOKEN_EXPIRATION_MINUTES}
cloud:
  aws:
    s3.bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_BUCKET_ACCESS_KEY}
      secret-key: ${AWS_S3_BUCKET_SECRET_KEY}
    region.static: ${AWS_S3_BUCKET_REGION}
    stack.auto: false
default:
  image:
    address: ${DEFAULT_IMAGE_URL}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      springframework:
        orm:
          jpa: DEBUG # 트랜잭션 로그 레벨 설정